### ISSUE TITLE
Error running makefile

### ISSUE THREAD

**Issue by RonsonRajan98** [nick-petrovsky/PYNQ-ZYBO#3]
I am having trouble running the makefile in this step.

Somewhy PYNQ referes base.bit file from BOARDDIR but do not build it automatically, so

$ cd ${HOME}/git-projects/PYNQ-ZYBO/Zybo
$ make

Also could you please upload a image that had hdmi+usbwebcam overlay for video streaming.
Thanks

**Comment by nick-petrovsky** [comment]
> I am having trouble running the makefile in this step.
> 
> Somewhy PYNQ referes base.bit file from BOARDDIR but do not build it automatically, so
> 
> $ cd ${HOME}/git-projects/PYNQ-ZYBO/Zybo $ make

I guessed it is already mentioned in [README.md](https://github.com/nick-petrovsky/PYNQ-ZYBO/blob/85f93725d19aeb0a250877757d76292506bfcdc7/README.md?plain=1#L153), if something isn't clear -- please make pull request.

> 
> Also could you please upload a image that had hdmi+usbwebcam overlay for video streaming. Thanks

I have no plans to develop additional overlays at the moment, there are lots of implementations with similar functionality. Good starting point is [this ](https://github.com/analogdevicesinc/hdl/tree/main/library/axi_hdmi_tx). After adaptation of IP-core, GStreamer-based scripts can be used for capturing video from USB camera.
